on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        requirements_path: "requirements.txt"
    - name: Copy files and so
      run: pwd
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
      
